### ISSUE TITLE
eorm: IN 查询支持

### ISSUE THREAD

**Issue by flycash** [gotomicro/eorm#101]
**仅限中文**

### 使用场景

在 WHERE 部分使用 IN 查询。目前来说，我们暂时不需要考虑子查询的问题，因为子查询的形态不同于普通的 IN 语句。

### 可行方案
```go
// 用户用起来
s.Where(C("Id").In(1, 2, 3)) // WHERE `id` IN (?, ?, ?)
s.Where(C("Id").NotIn(1, 2, 3)) // WHERE `id` NOT IN (?, ?, ?)
```

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by Stone-afk** [comment]
这 issue 我领了，哈哈
