### ISSUE TITLE
eorm: 支持基本类型作为返回值

### ISSUE THREAD

**Issue by flycash** [gotomicro/eorm#105]
**仅限中文**

### 使用场景

在有一些场景下我们会在 SELECT 里面使用聚合函数，例如：
```go
SELECT AVG(`age`) FROM users 
```
在这种情况下，我们会希望 Selector 能够返回基本类型：
```go
avgAge := NewSelector[int].Select(xxx).From(&User{}).Where(xxx).Get(ctx)
```
相比我们已经支持的用法，它的改动主要涉及到：
- 表名：早期我们是可以直接从泛型的类型参数里面解析得来，现在我们只能考虑引入 From 方法，并且 From 里面不再是接收一个 string 参数，而是一个结构体参数
- 结果集处理：在这种情况下，我们只能允许用户查询一个列，多余的列我们会返回错误。而这个单独的列，就要转化为基本类型

除了 Get，显然还需要支持 MultiGet。

而要支持的类型包括：
- string
- 基本类型
-  []byte

### 行业分析
在 Go 里面基本没有什么可以参考的东西，因为这是第一次采用泛型来解决聚合函数的问题。

### 可行方案

实际上，如果我们不考虑已有的 valuer 抽象的话，实现起来还是很容易的，我们只需要在 Get 和 MultiGet 里面进行类型判断，而后直接调用 Scan 方法，这也就是最简单的方法。

我大概评估了一下，如果我们希望将这个逻辑下沉到 valuer.SetFields 方法里面，那么还是比较棘手的。这种做法的好处是保持住了 valuer 抽象。

### 其它

- 你可以先提供一个草稿合并请求，它不需要有测试，然后我们在这个合并请求下讨论你的设计的优缺点
- 如果你是极客时间中实战训练营的学员，你可以直接联系我，我可以约一个会议详细解释这个需求。否则你可以考虑给我发邮件，预约一个时间，我也可以详细解释这个需求

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by Stone-afk** [comment]
11111

**Comment by Stone-afk** [comment]
比如说结构体: 
`type TestModel struct {
	Id        int64
	FirstName string
	Age       int8
	LastName  *sql.NullString
}`
我们查 Avg(`age`) 的时候，泛型得类型是否，受字段Age类型得约束呢？
