### ISSUE TITLE
eorm: AOP 接口设计

### ISSUE THREAD

**Issue by flycash** [gotomicro/eorm#114]
**仅限中文**

我在极客时间的实战训练营里面已经讲得很清楚了。设计文档后续补，TODO

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by Stone-afk** [comment]
明哥，这个 issue 不急的话分配给我吧 =.=

**Comment by Stone-afk** [comment]
大佬，不急的话aop的那两个都给我吧 =。=

**Comment by Stone-afk** [comment]
明哥，不着急的话aop给我了吧
