### ISSUE TITLE
支持使用组合定义模型

### ISSUE THREAD

**Issue by flycash** [gotomicro/eorm#70]
[设计文档](https://github.com/gotomicro/eorm/discussions/61)

**Comment by flyhigher139** [comment]
@flycash 老师，这个issue我认领过来做吧

**Comment by flycash** [comment]
ok，你需要可以分成好几个步骤来：
- 修改 model 部分，要计算出来组合形态下的 offset 和 indexes
- 修改 valuer 部分，这个部分原则上不用修改，只需要加一些测试进去
- 修改 CRUD 的几个，原则上也不需要修改，只需要加一些测试进去

**Comment by flyhigher139** [comment]
收到～

**Comment by flycash** [comment]
@flyhigher139 啥时候把测试补充一下？

**Comment by flyhigher139** [comment]
@flycash 老师，我周末前出一稿吧，这几天有些杂事，晚上没搞代码

**Comment by flyhigher139** [comment]
> @flyhigher139 啥时候把测试补充一下？

老师，测试用例已补充： #104

**Comment by flycash** [comment]
最后还有一个步骤，加上简单的增删改查集成测试

**Comment by flyhigher139** [comment]
> 最后还有一个步骤，加上简单的增删改查集成测试

好的~

**Comment by flyhigher139** [comment]
@flycash 集成测试已经添加
