### ISSUE TITLE
eorm: Delete 的执行

### ISSUE THREAD

**Issue by flycash** [gotomicro/eorm#92]
**仅限中文**

### 使用场景

很显然，到目前为止我们只支持了 SELECT 和 INSERT，在 DELETE 语句上，我们只支持了构造出来 DELETE 语句，但是没有支持发起 DELETE 查询并且返回结果。

DELETE 语句和 INSERT 语句在执行上并没有什么差距，所以可以直接将 Inserter 的执行代码复制一份过来。

但是你需要提供：
- 基于 sqlmock 的单元测试
- 集成测试

**Comment by mousseqin** [comment]
Deleter struct 还没有支持泛型，而且属性里少了session，是不是要一并修改？

**Comment by flycash** [comment]
是的

**Comment by flycash** [comment]
实际单纯从 Deleter 的角度来说，它不怎么需要泛型。不过保持一致就还是给它一个泛型。
